# Generated by Django 5.2.15 on 2026-06-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SiteMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('url_base', models.URLField()),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site monitorado',
                'verbose_name_plural': 'Sites monitorados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='mercado.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoColetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=500)),
                ('codigo_site', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercado.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercado.marca')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.sitemonitorado')),
            ],
            options={
                'verbose_name': 'Produto coletado',
                'verbose_name_plural': 'Produtos coletados',
                'ordering': ['nome_original'],
                'unique_together': {('site', 'url')},
            },
        ),
        migrations.CreateModel(
            name='ColetaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_antigo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nota_media', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('quantidade_avaliacoes', models.IntegerField(blank=True, null=True)),
                ('ranking_geral', models.IntegerField(blank=True, null=True)),
                ('ranking_categoria', models.IntegerField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('texto_disponibilidade', models.CharField(blank=True, max_length=200, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='mercado.produtocoletado')),
            ],
            options={
                'verbose_name': 'Coleta de produto',
                'verbose_name_plural': 'Coletas de produtos',
                'ordering': ['-data_coleta'],
            },
        ),
    ]
