# Generated by Django 5.2.15 on 2026-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocoletado',
            name='codigo_fabricante',
            field=models.CharField(blank=True, db_index=True, help_text='Código original do produto informado pelo fabricante.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='produtocoletado',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras EAN/GTIN do produto. Deve ser tratado como texto.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtocoletado',
            name='codigo_site',
            field=models.CharField(blank=True, help_text='Código interno do produto no site monitorado.', max_length=100, null=True),
        ),
    ]
