# Generated by Django 5.2.15 on 2026-06-13 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_produtocoletado_codigo_fabricante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricanteImportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('FABRICANTE', 'Fabricante'), ('IMPORTADOR', 'Importador'), ('DISTRIBUIDOR_OFICIAL', 'Distribuidor oficial'), ('OUTRO', 'Outro')], default='FABRICANTE', max_length=30)),
                ('site_oficial', models.URLField(blank=True, null=True)),
                ('pais_origem', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabricante / Importador',
                'verbose_name_plural': 'Fabricantes / Importadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produtocoletado',
            name='status_vinculo',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de validação'), ('VINCULADO', 'Vinculado ao produto referência'), ('DIVERGENTE', 'Divergente'), ('SEM_REFERENCIA', 'Sem referência encontrada')], default='PENDENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='produtocoletado',
            name='codigo_fabricante',
            field=models.CharField(blank=True, db_index=True, help_text='Código original do produto informado no site de venda.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='produtocoletado',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras EAN/GTIN informado no site de venda.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProdutoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_referencia', models.CharField(help_text='Nome oficial ou tratado do produto conforme fonte de referência.', max_length=500)),
                ('codigo_fabricante', models.CharField(blank=True, db_index=True, help_text='Código original informado pelo fabricante/importador.', max_length=150, null=True)),
                ('ean', models.CharField(blank=True, db_index=True, help_text='Código de barras EAN/GTIN. Deve ser tratado como texto.', max_length=20, null=True)),
                ('url_oficial', models.URLField(blank=True, help_text='URL da fonte oficial usada para validar o produto.', max_length=1000, null=True)),
                ('fonte_validacao', models.CharField(choices=[('SITE_FABRICANTE', 'Site do fabricante'), ('SITE_IMPORTADOR', 'Site do importador'), ('CATALOGO_OFICIAL', 'Catálogo oficial'), ('MANUAL_EMBALAGEM', 'Manual ou embalagem'), ('OUTRA', 'Outra fonte')], default='SITE_FABRICANTE', max_length=30)),
                ('status_validacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VALIDADO', 'Validado'), ('DIVERGENTE', 'Divergente'), ('SEM_REFERENCIA', 'Sem referência oficial')], default='PENDENTE', max_length=30)),
                ('observacao_validacao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercado.categoria')),
                ('fabricante_importador', models.ForeignKey(blank=True, help_text='Fabricante, importador ou distribuidor oficial responsável pelo produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercado.fabricanteimportador')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercado.marca')),
            ],
            options={
                'verbose_name': 'Produto referência',
                'verbose_name_plural': 'Produtos referência',
                'ordering': ['nome_referencia'],
            },
        ),
        migrations.AddField(
            model_name='produtocoletado',
            name='produto_referencia',
            field=models.ForeignKey(blank=True, help_text='Produto oficial/referência usado para comparar o mesmo item entre sites.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_coletados', to='mercado.produtoreferencia'),
        ),
    ]
