# Generated by Django 5.2.15 on 2026-06-14 23:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_fabricanteimportador_produtocoletado_status_vinculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_coleta', models.CharField(choices=[('MAIS_VENDIDOS', 'Mais vendidos'), ('CATEGORIA', 'Categoria'), ('BUSCA', 'Busca'), ('OUTRA', 'Outra')], default='MAIS_VENDIDOS', max_length=30)),
                ('nome_fonte', models.CharField(default='Mais vendidos', max_length=200)),
                ('url_base', models.URLField(blank=True, max_length=1000, null=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('limite_solicitado', models.IntegerField(blank=True, null=True)),
                ('max_paginas', models.IntegerField(blank=True, null=True)),
                ('paginas_processadas', models.IntegerField(default=0)),
                ('produtos_encontrados', models.IntegerField(default=0)),
                ('produtos_novos', models.IntegerField(default=0)),
                ('produtos_atualizados', models.IntegerField(default=0)),
                ('coletas_gravadas', models.IntegerField(default=0)),
                ('dry_run', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('EM_EXECUCAO', 'Em execução'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('SEM_DADOS', 'Sem dados')], default='EM_EXECUCAO', max_length=30)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_coleta', to='mercado.sitemonitorado')),
            ],
            options={
                'verbose_name': 'Execução de coleta',
                'verbose_name_plural': 'Execuções de coleta',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
