# Generated by Django 5.2.15 on 2026-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_execucaocoleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletaproduto',
            name='preco_prazo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço total a prazo/cartão, quando informado no site.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='coletaproduto',
            name='quantidade_parcelas',
            field=models.IntegerField(blank=True, help_text='Quantidade máxima de parcelas informada no site.', null=True),
        ),
        migrations.AddField(
            model_name='coletaproduto',
            name='valor_parcela',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da parcela informada no site.', max_digits=12, null=True),
        ),
    ]
