# Generated by Django 5.2.15 on 2026-06-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_coletaproduto_preco_prazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlvoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome interno para identificar esta coleta.', max_length=255)),
                ('coletor', models.CharField(choices=[('loja_mecanico', 'Loja do Mecânico'), ('dutra_maquinas', 'Dutra Máquinas')], help_text='Qual coletor será usado para esta URL.', max_length=50)),
                ('nome_fonte', models.CharField(help_text='Nome da fonte que aparecerá nos relatórios. Ex: Dutra - Alicates.', max_length=255)),
                ('url', models.URLField(help_text='URL da categoria, busca, campanha ou página que será coletada.', max_length=1000)),
                ('ativo', models.BooleanField(default=True)),
                ('limite', models.PositiveIntegerField(default=500, help_text='Quantidade máxima de produtos a coletar.')),
                ('max_paginas', models.PositiveIntegerField(default=10, help_text='Quantidade máxima de páginas a percorrer.')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de execução. Menor número roda primeiro.')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('ultima_situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alvos_coleta', to='mercado.categoria')),
                ('site_monitorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alvos_coleta', to='mercado.sitemonitorado')),
            ],
            options={
                'verbose_name': 'Alvo de coleta',
                'verbose_name_plural': 'Alvos de coleta',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
