# Generated by Django 5.2.15 on 2026-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_alvocoleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletaproduto',
            name='estoque',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
