# Generated by Django 5.2.15 on 2026-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_coletaproduto_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alvocoleta',
            options={'ordering': ['servico_coleta', 'ordem', 'id'], 'verbose_name': 'Alvo de coleta', 'verbose_name_plural': 'Alvos de coleta'},
        ),
        migrations.AddField(
            model_name='alvocoleta',
            name='servico_coleta',
            field=models.CharField(db_index=True, default='servico_01', help_text='Identificador do agente/serviço responsável por executar este alvo. Ex: servico_01.', max_length=50),
        ),
    ]
