# Generated by Django 5.2.15 on 2026-06-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_alter_alvocoleta_options_alvocoleta_servico_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvocoleta',
            name='coletor',
            field=models.CharField(choices=[('loja_mecanico', 'Loja do Mecânico'), ('dutra_maquinas', 'Dutra Máquinas'), ('ferramentas_kennedy', 'Ferramentas Kennedy')], help_text='Qual coletor será usado para esta URL.', max_length=50),
        ),
    ]
