# Generated by Django 5.2.15 on 2026-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_alter_alvocoleta_coletor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvocoleta',
            name='coletor',
            field=models.CharField(choices=[('loja_mecanico', 'Loja do Mecânico'), ('dutra_maquinas', 'Dutra Máquinas'), ('ferramentas_kennedy', 'Ferramentas Kennedy'), ('palacio_ferramentas', 'Palácio das Ferramentas'), ('fg_ferramentas', 'FG - Ferramentas Gerais')], help_text='Qual coletor será usado para esta URL.', max_length=50),
        ),
    ]
